### ISSUE TITLE
Type Error when running the script

### ISSUE THREAD

**Issue by docstar1** [EKarton/Lecture-Video-to-PDF#1]
Hi
Thank you for sharing the code. I tried executing the script as per the instructions in readme file. It works fine if run with the example subtitle files (subtitles_1, subtitles_2, etc) are used. But when using my subtitle file with video, the program throws the following error (link to subtitle file that was used: https://github.com/docstar1/Lecture-Video-to-PDF/blob/2daed0bc3426db515ad8da3ef3611834789c23db/tests/subtitles/subtitles_3.vtt):
Traceback (most recent call last):
  File "src/main.py", line 77, in <module>
    runner.run(sys.argv[1:])
  File "src/main.py", line 47, in run
    video_segment_finder, video_filepath, subtitle_parser, output_filepath
  File "src/main.py", line 61, in __run__
    segments = segment_finder.get_subtitle_segments(subtitle_breaks)
  File "..\PycharmProjects\Lecture-Video-to-PDF\src\subtitle_segment_finder.py", line 96, in get_subtitle_segments
    pos = self.__get_part_position_of_time_break__(time_break)
  File "..\PycharmProjects\Lecture-Video-to-PDF\src\subtitle_segment_finder.py", line 152, in __get_part_position_of_time_break__
    part = self.parts[part_index]
TypeError: list indices must be integers or slices, not NoneType

**Comment by EKarton** [comment]
Hi @docstar1 thanks for creating an issue. I was able to reproduce the crash by running `python3 src/main.py tests/videos/input_3.mp4 -s tests/subtitles/subtitles_3.vtt -o output.pdf`. The cause of the crash happen to be from the `subtitle_3` file, where it is missing subtitles between times 00:00:50.125 and 00:01:23.670:

```
11
00:00:43.772 --> 00:00:50.125
centimeter or so off the
aluminum sheets.

12
00:01:23.670 --> 00:01:30.706
Hook a wire up to each piece of
tinfoil. You can
```

and it was trying to find subtitles at time 00:00:56. I've made the fix at https://github.com/EKarton/Lecture-Video-to-PDF/pull/2. Please let me know if you encounter any more bugs. Thank you

**Comment by docstar1** [comment]
Wow, the fix worked great. I should have checked the subtitle file first. 
Thank you! Here's the link to the video file for the subtitle as you requested: https://www.dropbox.com/s/ts1iimdb5pai8ps/input_111.mp4?dl=0 (Will delete the file after a week due to copyright issues)
Thanks again!
