### ISSUE TITLE
Feature Request: Extract slides without subtitles

### ISSUE THREAD

**Issue by MaZED-UP** [EKarton/Lecture-Video-to-PDF#11]
Hi! I like the idea of your project but it's not what I actually want.

I have a few lectures videos **without** subtitle files and I'm not interested in having subtitles in the PDF document either.
I just want to to obtain a document with the slides in landscape orientation.

Please consider adding the option to achieve the mentioned result.

___
**Side note**: I noticed that your program depends on CPU power. Have you ever thought about utilizing the GPU instead?

**Comment by MaZED-UP** [comment]
Please correct me if I'm not aware of that feature in the first place.

**Comment by EKarton** [comment]
Hi, thanks for creating the feature request. It's a neat feature to have, and I think it can be implemented. I'll keep you posted once the PR is up. Thanks

**Comment by EKarton** [comment]
Hi @MaZED-UP the PR for the change (https://github.com/EKarton/Lecture-Video-to-PDF/pull/12) has been merged in. Let me know if you find any bugs. Thanks
