### ISSUE TITLE
SRT files

### ISSUE THREAD

**Issue by Legislate3030** [EKarton/Lecture-Video-to-PDF#3]
Hi, I got

```
Getting subtitles for each frame
Traceback (most recent call last):
  File "src/main.py", line 80, in <module>
    runner.run(sys.argv[1:])
  File "src/main.py", line 46, in run
    self.__run__(
  File "src/main.py", line 61, in __run__
    segment_finder = SubtitleSegmentFinder(subtitle_parser.get_subtitle_parts())
  File "C:\Users\Tilman\AppData\Local\Programs\Python\Python38\src\subtitle_segment_finder.py", line 52, in get_subtitle_parts
    for caption in webvtt.read(self.input_file):
  File "C:\Users\Tilman\AppData\Local\Programs\Python\Python38\lib\site-packages\webvtt\webvtt.py", line 60, in read
    parser = WebVTTParser().read(file)
  File "C:\Users\Tilman\AppData\Local\Programs\Python\Python38\lib\site-packages\webvtt\parsers.py", line 25, in read
    self._validate(content)
  File "C:\Users\Tilman\AppData\Local\Programs\Python\Python38\lib\site-packages\webvtt\parsers.py", line 258, in _validate
    raise MalformedFileError('The file does not have a valid format')
webvtt.errors.MalformedFileError: The file does not have a valid format
```
when trying to use a .srt subtitle file. Is it possible to add support for that?

**Comment by EKarton** [comment]
Hi @tharos96 thanks for reaching out. It's a good suggestion and we can add support for a `.srt` subtitle file. I'll keep you posted once a PR is out with the new feature. Thanks

**Comment by Legislate3030** [comment]
Great, thanks!

**Comment by EKarton** [comment]
Hi @tharos96 the PR for supporting `.srt` subtitles has been merged in (https://github.com/EKarton/Lecture-Video-to-PDF/pull/5) and is ready to be used. Please let me know if you encounter any bugs. Thanks

**Comment by tharos96** [comment]
```
C:\Users\user\AppData\Local\Programs\Python\Python38>python.exe src/main.py "D:\Downloads\vid1.m4v" -s "D:\Downloads\subt1.srt" -o output.pdf
Getting selected frames
Getting subtitles for each frame
Traceback (most recent call last):
  File "src/main.py", line 80, in <module>
    runner.run(sys.argv[1:])
  File "src/main.py", line 46, in run
    self.__run__(
  File "src/main.py", line 61, in __run__
    segment_finder = SubtitleSegmentFinder(subtitle_parser.get_subtitle_parts())
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\src\subtitle_segment_finder.py", line 52, in get_subtitle_parts
    for caption in webvtt.read(self.input_file):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\webvtt\webvtt.py", line 60, in read
    parser = WebVTTParser().read(file)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\webvtt\parsers.py", line 25, in read
    self._validate(content)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\webvtt\parsers.py", line 258, in _validate
    raise MalformedFileError('The file does not have a valid format')
webvtt.errors.MalformedFileError: The file does not have a valid format
```

I'm not quite sure if this is due to .srt but it did not work for me.

**Comment by Legislate3030** [comment]
```
C:\Users\user\AppData\Local\Programs\Python\Python38>python.exe src/main.py "D:\Downloads\vid1.m4v" -s "D:\Downloads\subt1.srt" -o output_srt.pdf
Getting selected frames
Getting subtitles for each frame
Merging frames and subtitles
C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fpdf\fpdf.py:710: UserWarning: Substitutting Arial by core font Helvetica
  warnings.warn("Substitutting Arial by core font Helvetica")
Traceback (most recent call last):
  File "src/main.py", line 85, in <module>
    runner.run(sys.argv[1:])
  File "src/main.py", line 51, in run
    self.__run__(
  File "src/main.py", line 80, in __run__
    pdf = printer.generate_pdf(video_subtitle_pages, output_filepath)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\src\content_segment_exporter.py", line 56, in generate_pdf
    pdf.multi_cell(0, 10, pages[i].text)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fpdf\fpdf.py", line 129, in wrapper
    return fn(self, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fpdf\fpdf.py", line 1100, in multi_cell
    txt = self.normalize_text(txt)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fpdf\fpdf.py", line 1473, in normalize_text
    return txt.encode(self.core_fonts_encoding).decode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0178' in position 1267: ordinal not in range(256)
```

I get this when trying srt.

**Comment by Legislate3030** [comment]
Possibly because of German Umlaute - Ä, Ö, Ü?

**Comment by Legislate3030** [comment]
I also still get accumulation of text as shown in the pictures (77 slides overall).
As you can see there is a bit of text later on again but it does not at all relate to the actual time codes. As this is the output of using a .vtt file (converted from .srt) this might be down to the conversion? When checking the file it seems fine though. I attached it incase you want to check. The video is 50 minutes long and there should be evenly distributed subtitles throughout the video and slides.
[subt1.vtt.txt](https://github.com/EKarton/Lecture-Video-to-PDF/files/7618120/subt1.vtt.txt)
Also, how can I avoid duplicate slides?
Potentially this is solved by me getting it to work with the original .srt file. Any help is appreciated!
![grafik](https://user-images.githubusercontent.com/28876315/143867509-d1a6259d-e1bd-454e-a847-363f84bbfb0c.png)
![grafik](https://user-images.githubusercontent.com/28876315/143867533-609677f9-34d0-4611-b3f8-5ff8348e34c5.png)

**Comment by EKarton** [comment]
> ```
> C:\Users\user\AppData\Local\Programs\Python\Python38>python.exe src/main.py "D:\Downloads\vid1.m4v" -s "D:\Downloads\subt1.srt" -o output_srt.pdf
> Getting selected frames
> Getting subtitles for each frame
> Merging frames and subtitles
> C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fpdf\fpdf.py:710: UserWarning: Substitutting Arial by core font Helvetica
>   warnings.warn("Substitutting Arial by core font Helvetica")
> Traceback (most recent call last):
>   File "src/main.py", line 85, in <module>
>     runner.run(sys.argv[1:])
>   File "src/main.py", line 51, in run
>     self.__run__(
>   File "src/main.py", line 80, in __run__
>     pdf = printer.generate_pdf(video_subtitle_pages, output_filepath)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\src\content_segment_exporter.py", line 56, in generate_pdf
>     pdf.multi_cell(0, 10, pages[i].text)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fpdf\fpdf.py", line 129, in wrapper
>     return fn(self, *args, **kwargs)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fpdf\fpdf.py", line 1100, in multi_cell
>     txt = self.normalize_text(txt)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fpdf\fpdf.py", line 1473, in normalize_text
>     return txt.encode(self.core_fonts_encoding).decode("latin-1")
> UnicodeEncodeError: 'latin-1' codec can't encode character '\u0178' in position 1267: ordinal not in range(256)
> ```
> 
> I get this when trying srt.

I think to fix this bug, from https://pyfpdf.readthedocs.io/en/latest/Unicode/index.html, I can add unicode support in the fpdf builder. I'll add support for unicode characters to the current PDF builder. Thanks for letting me know about the bug

**Comment by EKarton** [comment]
> I also still get accumulation of text as shown in the pictures (77 slides overall). As you can see there is a bit of text later on again but it does not at all relate to the actual time codes. As this is the output of using a .vtt file (converted from .srt) this might be down to the conversion? When checking the file it seems fine though. I attached it incase you want to check. The video is 50 minutes long and there should be evenly distributed subtitles throughout the video and slides. [subt1.vtt.txt](https://github.com/EKarton/Lecture-Video-to-PDF/files/7618120/subt1.vtt.txt) Also, how can I avoid duplicate slides? Potentially this is solved by me getting it to work with the original .srt file. Any help is appreciated! ![grafik](https://user-images.githubusercontent.com/28876315/143867509-d1a6259d-e1bd-454e-a847-363f84bbfb0c.png) ![grafik](https://user-images.githubusercontent.com/28876315/143867533-609677f9-34d0-4611-b3f8-5ff8348e34c5.png)

Thanks a lot for letting me know about this edge case. I agree, the subtitles should be more balanced between the different frames.

For background info, after getting the frames and its timestamps, it finds the index in the subtitle file with that timestamp. After finding the index of the subtitle that points to that frame's timeframe, it tries to find the closest `.` left or right of that index in the attempt to find the closest closing sentence.

But in the subtitles above, since there's no `.`, it will try to find the `.` until it reaches the end of the subtitle file. It will then return the index of the end of the subtitle file.

The fix would probably to return the position in the subtitle corresponding to the frame's timestamp if no `.` is found. I'll do that and see how it goes. Thanks for letting me know about this edge case.

**Comment by EKarton** [comment]
Hi @tharos96 a fix was made to address the two issues and is ready to be used (https://github.com/EKarton/Lecture-Video-to-PDF/pull/7). Please let me know if you encounter any bugs. Thanks

**Comment by Legislate3030** [comment]
Great to hear, thanks! 
The subtitles were automatically generated and I was not aware that it's trying to find the closest closing sentence.
I will report back if I encounter any issues.
