### ISSUE TITLE
Cropped slides in output.pdf

### ISSUE THREAD

**Issue by Legislate3030** [EKarton/Lecture-Video-to-PDF#4]
```
python.exe src/main.py "D:\Downloads\vid1.m4v" -s "D:\Downloads\subt1.vtt" -o output.pdf

C:\Users\User\AppData\Local\Programs\Python\Python38>python.exe src/main.py "D:\Downloads\vid1.m4v" -s "D:\Downloads\subt1.vtt" -o output.pdf
Getting selected frames
Getting subtitles for each frame
Merging frames and subtitles
C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\fpdf\fpdf.py:710: UserWarning: Substitutting Arial by core font Helvetica
  warnings.warn("Substitutting Arial by core font Helvetica")
```

resulted in cropped slides in the output.pdf like this:
![grafik](https://user-images.githubusercontent.com/28876315/142372908-32e4f508-2283-499b-8b49-521bee518cc5.png)

Also, the subtitles are more or less split into two major parts. They were converted from .srt to .vtt via https://www.happyscribe.com and have the following exemplary format:

> 
> 1090
> 00:36:26.960 --> 00:36:29.660
> inzwischen wird das war schon ein

**Comment by EKarton** [comment]
Hi @tharos96 thanks for letting me know about the bug. For the first bug (the one with the cropped slides), I think it is fixable by setting the max height of the image in the PDF. Unfortunately, for the second bug, I am not too sure what it was meant by the subtitles split into two major parts. Could you provide me an example of where the subtitles were split in the auto-generated PDF? Thanks

**Comment by Legislate3030** [comment]
Unfortunately I deleted the files by now. One half of the subtitles was on a single page full of text - before and after that there were the bugged cropped slides - and the other half of subtitles was on another single page full of text.

**Comment by EKarton** [comment]
Hi @tharos96 the bug for the enlarged images in the PDF has been fixed (https://github.com/EKarton/Lecture-Video-to-PDF/pull/6). Please let me know if you encounter any more bugs. Thank you
