### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by s-bhagwat** [EKarton/Lecture-Video-to-PDF#8]
I'm getting this error - 
In my subtitle file I dont have any dots (.) I think that is the problem,
### This is the output

```Getting selected frames
Number of frames: 103
Getting subtitles for each frame
Traceback (most recent call last):
  File "src/main.py", line 87, in <module>
    runner.run(sys.argv[1:])
  File "src/main.py", line 51, in run
    self.__run__(
  File "src/main.py", line 70, in __run__
    segments = segment_finder.get_subtitle_segments(subtitle_breaks)
  File "D:\Study\Sixth-Sem\Lecture-Video-to-PDF\src\subtitle_segment_finder.py", line 42, in get_subtitle_segments
    pos = self.__get_part_position_of_time_break__(time_break)
  File "D:\Study\Sixth-Sem\Lecture-Video-to-PDF\src\subtitle_segment_finder.py", line 122, in __get_part_position_of_time_break__
    if self.parts[right_part_index].text[right_part_char_index] == ".":
IndexError: string index out of range```

**Comment by EKarton** [comment]
Hi @s-bhagwat thanks for letting me know about this issue. Unfortunately, I was not able to reproduce this issue with a subtitle file without periods. Could you attach a copy of the video and its subtitle file you were trying to transcribe? Thanks

**Comment by s-bhagwat** [comment]
https://drive.google.com/drive/folders/17DC85DsED7GeOJ-qmvlcYj5m__I4hSoF?usp=sharing

It is a youtube video with auto subs I have tested it after cutting it to 10 mins.

https://youtu.be/KN6OSdUfgyA

**Comment by EKarton** [comment]
Hi @s-bhagwat thanks for filing the bug, and for providing the video and subtitle files. I was able to reproduce the error. A PR was made and merged in to fix the error (https://github.com/EKarton/Lecture-Video-to-PDF/pull/10).

Unfortunately, the provided subtitle file didn't generate the best PDF. I would maybe suggest using another tool to get subtitles from a youtube video. I found https://downsub.com. From their website, I was able to generate subtitles for the youtube video, and generate a PDF that looked like:

[output.pdf](https://github.com/EKarton/Lecture-Video-to-PDF/files/7875851/output.pdf)

On the other hand, please let me know if you encounter any bugs. Thanks

**Comment by s-bhagwat** [comment]
Thanks my issue is resolved !
I'm closing this issue.
